==23681== Helgrind, a thread error detector
==23681== Copyright (C) 2007-2017, and GNU GPL'd, by OpenWorks LLP et al.
==23681== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==23681== Command: ./bin/cpu ./configs/prueba.config
==23681== Parent PID: 17387
==23681== 
==23681== ---Thread-Announcement------------------------------------------
==23681== 
==23681== Thread #3 was created
==23681==    at 0x49A39F3: clone (clone.S:76)
==23681==    by 0x49A48EE: __clone_internal (clone-internal.c:83)
==23681==    by 0x49126D8: create_thread (pthread_create.c:295)
==23681==    by 0x49131FF: pthread_create@@GLIBC_2.34 (pthread_create.c:828)
==23681==    by 0x4853767: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==23681==    by 0x10DF0C: hilos_cpu (server.c:227)
==23681==    by 0x10A919: main (main.c:23)
==23681== 
==23681== ---Thread-Announcement------------------------------------------
==23681== 
==23681== Thread #2 was created
==23681==    at 0x49A39F3: clone (clone.S:76)
==23681==    by 0x49A48EE: __clone_internal (clone-internal.c:83)
==23681==    by 0x49126D8: create_thread (pthread_create.c:295)
==23681==    by 0x49131FF: pthread_create@@GLIBC_2.34 (pthread_create.c:828)
==23681==    by 0x4853767: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==23681==    by 0x10DEA6: hilos_cpu (server.c:219)
==23681==    by 0x10A919: main (main.c:23)
==23681== 
==23681== ---Thread-Announcement------------------------------------------
==23681== 
==23681== Thread #1 is the program's root thread
==23681== 
==23681== ----------------------------------------------------------------
==23681== 
==23681== Possible data race during write of size 1 at 0x4AAA6C0 by thread #3
==23681== Locks held: none
==23681==    at 0x4859796: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==23681==    by 0x4909664: _IO_new_file_xsputn (fileops.c:1235)
==23681==    by 0x4909664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==23681==    by 0x48F314C: outstring_func (vfprintf-internal.c:239)
==23681==    by 0x48F314C: __vfprintf_internal (vfprintf-internal.c:1263)
==23681==    by 0x48DE79E: printf (printf.c:33)
==23681==    by 0x11043A: crear_conexion (sockets.c:163)
==23681==    by 0x10DC02: cliente_cpu_memoria (server.c:137)
==23681==    by 0x10DD9E: funcion_hilo_cliente_memoria (server.c:185)
==23681==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==23681==    by 0x4912AC2: start_thread (pthread_create.c:442)
==23681==    by 0x49A3A03: clone (clone.S:100)
==23681== 
==23681== This conflicts with a previous write of size 1 by thread #2
==23681== Locks held: none
==23681==    at 0x48597B4: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==23681==    by 0x4909664: _IO_new_file_xsputn (fileops.c:1235)
==23681==    by 0x4909664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==23681==    by 0x48F500B: outstring_func (vfprintf-internal.c:239)
==23681==    by 0x48F500B: __vfprintf_internal (vfprintf-internal.c:1517)
==23681==    by 0x48DE79E: printf (printf.c:33)
==23681==    by 0x4876800: txt_write_in_stdout (in /usr/lib/libcommons.so)
==23681==    by 0x4877570: _log_write_in_level (in /usr/lib/libcommons.so)
==23681==    by 0x4877027: log_trace (in /usr/lib/libcommons.so)
==23681==    by 0x110083: iniciar_servidor (sockets.c:49)
==23681==  Address 0x4aaa6c0 is 16 bytes inside a block of size 1,024 alloc'd
==23681==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==23681==    by 0x48FCBA3: _IO_file_doallocate (filedoalloc.c:101)
==23681==    by 0x490BCDF: _IO_doallocbuf (genops.c:347)
==23681==    by 0x490AF5F: _IO_file_overflow@@GLIBC_2.2.5 (fileops.c:744)
==23681==    by 0x49096D4: _IO_new_file_xsputn (fileops.c:1243)
==23681==    by 0x49096D4: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==23681==    by 0x48F500B: outstring_func (vfprintf-internal.c:239)
==23681==    by 0x48F500B: __vfprintf_internal (vfprintf-internal.c:1517)
==23681==    by 0x48DE79E: printf (printf.c:33)
==23681==    by 0x4876800: txt_write_in_stdout (in /usr/lib/libcommons.so)
==23681==    by 0x4877570: _log_write_in_level (in /usr/lib/libcommons.so)
==23681==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==23681==    by 0x10A8C6: main (main.c:21)
==23681==  Block was alloc'd by thread #1
==23681== 
==23681== ----------------------------------------------------------------
==23681== 
==23681== Possible data race during write of size 1 at 0x4AABE07 by thread #3
==23681== Locks held: none
==23681==    at 0x4859796: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==23681==    by 0x4909664: _IO_new_file_xsputn (fileops.c:1235)
==23681==    by 0x4909664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==23681==    by 0x48FDA9C: fputs (iofputs.c:38)
==23681==    by 0x48767C6: txt_write_in_file (in /usr/lib/libcommons.so)
==23681==    by 0x4877522: _log_write_in_level (in /usr/lib/libcommons.so)
==23681==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==23681==    by 0x11030B: cliente_handshake (sockets.c:127)
==23681==    by 0x10DC41: cliente_cpu_memoria (server.c:144)
==23681==    by 0x10DD9E: funcion_hilo_cliente_memoria (server.c:185)
==23681==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==23681==    by 0x4912AC2: start_thread (pthread_create.c:442)
==23681==    by 0x49A3A03: clone (clone.S:100)
==23681== 
==23681== This conflicts with a previous write of size 1 by thread #2
==23681== Locks held: none
==23681==    at 0x4859796: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==23681==    by 0x4909664: _IO_new_file_xsputn (fileops.c:1235)
==23681==    by 0x4909664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==23681==    by 0x48FDA9C: fputs (iofputs.c:38)
==23681==    by 0x48767C6: txt_write_in_file (in /usr/lib/libcommons.so)
==23681==    by 0x4877522: _log_write_in_level (in /usr/lib/libcommons.so)
==23681==    by 0x4877027: log_trace (in /usr/lib/libcommons.so)
==23681==    by 0x110083: iniciar_servidor (sockets.c:49)
==23681==    by 0x10D8E0: servidor_CPU_Kernel (server.c:72)
==23681==  Address 0x4aabe07 is 55 bytes inside a block of size 4,096 alloc'd
==23681==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==23681==    by 0x48FCBA3: _IO_file_doallocate (filedoalloc.c:101)
==23681==    by 0x490BCDF: _IO_doallocbuf (genops.c:347)
==23681==    by 0x490AF5F: _IO_file_overflow@@GLIBC_2.2.5 (fileops.c:744)
==23681==    by 0x49096D4: _IO_new_file_xsputn (fileops.c:1243)
==23681==    by 0x49096D4: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==23681==    by 0x48FDA9C: fputs (iofputs.c:38)
==23681==    by 0x48767C6: txt_write_in_file (in /usr/lib/libcommons.so)
==23681==    by 0x4877522: _log_write_in_level (in /usr/lib/libcommons.so)
==23681==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==23681==    by 0x10A8C6: main (main.c:21)
==23681==  Block was alloc'd by thread #1
==23681== 
==23681== ----------------------------------------------------------------
==23681== 
==23681== Possible data race during write of size 1 at 0x4AAA6C1 by thread #3
==23681== Locks held: none
==23681==    at 0x48597B4: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==23681==    by 0x4909664: _IO_new_file_xsputn (fileops.c:1235)
==23681==    by 0x4909664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==23681==    by 0x48F500B: outstring_func (vfprintf-internal.c:239)
==23681==    by 0x48F500B: __vfprintf_internal (vfprintf-internal.c:1517)
==23681==    by 0x48DE79E: printf (printf.c:33)
==23681==    by 0x4876800: txt_write_in_stdout (in /usr/lib/libcommons.so)
==23681==    by 0x4877570: _log_write_in_level (in /usr/lib/libcommons.so)
==23681==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==23681==    by 0x11030B: cliente_handshake (sockets.c:127)
==23681==    by 0x10DC41: cliente_cpu_memoria (server.c:144)
==23681==    by 0x10DD9E: funcion_hilo_cliente_memoria (server.c:185)
==23681==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==23681==    by 0x4912AC2: start_thread (pthread_create.c:442)
==23681== 
==23681== This conflicts with a previous write of size 1 by thread #2
==23681== Locks held: none
==23681==    at 0x48597B4: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==23681==    by 0x4909664: _IO_new_file_xsputn (fileops.c:1235)
==23681==    by 0x4909664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==23681==    by 0x48F500B: outstring_func (vfprintf-internal.c:239)
==23681==    by 0x48F500B: __vfprintf_internal (vfprintf-internal.c:1517)
==23681==    by 0x48DE79E: printf (printf.c:33)
==23681==    by 0x4876800: txt_write_in_stdout (in /usr/lib/libcommons.so)
==23681==    by 0x4877570: _log_write_in_level (in /usr/lib/libcommons.so)
==23681==    by 0x4877027: log_trace (in /usr/lib/libcommons.so)
==23681==    by 0x110083: iniciar_servidor (sockets.c:49)
==23681==  Address 0x4aaa6c1 is 17 bytes inside a block of size 1,024 alloc'd
==23681==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==23681==    by 0x48FCBA3: _IO_file_doallocate (filedoalloc.c:101)
==23681==    by 0x490BCDF: _IO_doallocbuf (genops.c:347)
==23681==    by 0x490AF5F: _IO_file_overflow@@GLIBC_2.2.5 (fileops.c:744)
==23681==    by 0x49096D4: _IO_new_file_xsputn (fileops.c:1243)
==23681==    by 0x49096D4: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==23681==    by 0x48F500B: outstring_func (vfprintf-internal.c:239)
==23681==    by 0x48F500B: __vfprintf_internal (vfprintf-internal.c:1517)
==23681==    by 0x48DE79E: printf (printf.c:33)
==23681==    by 0x4876800: txt_write_in_stdout (in /usr/lib/libcommons.so)
==23681==    by 0x4877570: _log_write_in_level (in /usr/lib/libcommons.so)
==23681==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==23681==    by 0x10A8C6: main (main.c:21)
==23681==  Block was alloc'd by thread #1
==23681== 
==23681== ---Thread-Announcement------------------------------------------
==23681== 
==23681== Thread #4 was created
==23681==    at 0x49A39F3: clone (clone.S:76)
==23681==    by 0x49A48EE: __clone_internal (clone-internal.c:83)
==23681==    by 0x49126D8: create_thread (pthread_create.c:295)
==23681==    by 0x49131FF: pthread_create@@GLIBC_2.34 (pthread_create.c:828)
==23681==    by 0x4853767: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==23681==    by 0x10A991: iniciar_cpu (cicloDeInstruccion.c:19)
==23681==    by 0x10A92A: main (main.c:25)
==23681== 
==23681== ---Thread-Announcement------------------------------------------
==23681== 
==23681== Thread #5 was created
==23681==    at 0x49A39F3: clone (clone.S:76)
==23681==    by 0x49A48EE: __clone_internal (clone-internal.c:83)
==23681==    by 0x49126D8: create_thread (pthread_create.c:295)
==23681==    by 0x49131FF: pthread_create@@GLIBC_2.34 (pthread_create.c:828)
==23681==    by 0x4853767: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==23681==    by 0x10A9D5: iniciar_cpu (cicloDeInstruccion.c:26)
==23681==    by 0x10A92A: main (main.c:25)
==23681== 
==23681== ----------------------------------------------------------------
==23681== 
==23681== Possible data race during write of size 1 at 0x4AAA6C3 by thread #4
==23681== Locks held: none
==23681==    at 0x4859796: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==23681==    by 0x4909664: _IO_new_file_xsputn (fileops.c:1235)
==23681==    by 0x4909664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==23681==    by 0x48FEF1B: puts (ioputs.c:40)
==23681==    by 0x10E977: send_ciclo_nuevo (serializacion.c:190)
==23681==    by 0x10AA5C: ciclo_de_instruccion (cicloDeInstruccion.c:45)
==23681==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==23681==    by 0x4912AC2: start_thread (pthread_create.c:442)
==23681==    by 0x49A3A03: clone (clone.S:100)
==23681== 
==23681== This conflicts with a previous write of size 1 by thread #5
==23681== Locks held: none
==23681==    at 0x48597B4: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==23681==    by 0x4909664: _IO_new_file_xsputn (fileops.c:1235)
==23681==    by 0x4909664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==23681==    by 0x48F500B: outstring_func (vfprintf-internal.c:239)
==23681==    by 0x48F500B: __vfprintf_internal (vfprintf-internal.c:1517)
==23681==    by 0x48DE79E: printf (printf.c:33)
==23681==    by 0x4876800: txt_write_in_stdout (in /usr/lib/libcommons.so)
==23681==    by 0x4877570: _log_write_in_level (in /usr/lib/libcommons.so)
==23681==    by 0x48770FF: log_debug (in /usr/lib/libcommons.so)
==23681==    by 0x10E0DC: recibir_kernel_interrupt (server.c:271)
==23681==  Address 0x4aaa6c3 is 19 bytes inside a block of size 1,024 alloc'd
==23681==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==23681==    by 0x48FCBA3: _IO_file_doallocate (filedoalloc.c:101)
==23681==    by 0x490BCDF: _IO_doallocbuf (genops.c:347)
==23681==    by 0x490AF5F: _IO_file_overflow@@GLIBC_2.2.5 (fileops.c:744)
==23681==    by 0x49096D4: _IO_new_file_xsputn (fileops.c:1243)
==23681==    by 0x49096D4: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==23681==    by 0x48F500B: outstring_func (vfprintf-internal.c:239)
==23681==    by 0x48F500B: __vfprintf_internal (vfprintf-internal.c:1517)
==23681==    by 0x48DE79E: printf (printf.c:33)
==23681==    by 0x4876800: txt_write_in_stdout (in /usr/lib/libcommons.so)
==23681==    by 0x4877570: _log_write_in_level (in /usr/lib/libcommons.so)
==23681==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==23681==    by 0x10A8C6: main (main.c:21)
==23681==  Block was alloc'd by thread #1
==23681== 
==23681== ----------------------------------------------------------------
==23681== 
==23681== Possible data race during write of size 1 at 0x4AAA6CE by thread #4
==23681== Locks held: none
==23681==    at 0x48597B4: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==23681==    by 0x4909664: _IO_new_file_xsputn (fileops.c:1235)
==23681==    by 0x4909664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==23681==    by 0x48F3CA8: outstring_func (vfprintf-internal.c:239)
==23681==    by 0x48F3CA8: __vfprintf_internal (vfprintf-internal.c:1516)
==23681==    by 0x48DE79E: printf (printf.c:33)
==23681==    by 0x10EB1A: send_paquete_syscall_sin_parametros (serializacion.c:237)
==23681==    by 0x10EBC6: send_paquete_syscall (serializacion.c:254)
==23681==    by 0x10E98B: send_ciclo_nuevo (serializacion.c:191)
==23681==    by 0x10AA5C: ciclo_de_instruccion (cicloDeInstruccion.c:45)
==23681==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==23681==    by 0x4912AC2: start_thread (pthread_create.c:442)
==23681==    by 0x49A3A03: clone (clone.S:100)
==23681== 
==23681== This conflicts with a previous write of size 1 by thread #5
==23681== Locks held: none
==23681==    at 0x48597B4: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==23681==    by 0x4909664: _IO_new_file_xsputn (fileops.c:1235)
==23681==    by 0x4909664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==23681==    by 0x48F500B: outstring_func (vfprintf-internal.c:239)
==23681==    by 0x48F500B: __vfprintf_internal (vfprintf-internal.c:1517)
==23681==    by 0x48DE79E: printf (printf.c:33)
==23681==    by 0x4876800: txt_write_in_stdout (in /usr/lib/libcommons.so)
==23681==    by 0x4877570: _log_write_in_level (in /usr/lib/libcommons.so)
==23681==    by 0x48770FF: log_debug (in /usr/lib/libcommons.so)
==23681==    by 0x10E0DC: recibir_kernel_interrupt (server.c:271)
==23681==  Address 0x4aaa6ce is 30 bytes inside a block of size 1,024 alloc'd
==23681==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==23681==    by 0x48FCBA3: _IO_file_doallocate (filedoalloc.c:101)
==23681==    by 0x490BCDF: _IO_doallocbuf (genops.c:347)
==23681==    by 0x490AF5F: _IO_file_overflow@@GLIBC_2.2.5 (fileops.c:744)
==23681==    by 0x49096D4: _IO_new_file_xsputn (fileops.c:1243)
==23681==    by 0x49096D4: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==23681==    by 0x48F500B: outstring_func (vfprintf-internal.c:239)
==23681==    by 0x48F500B: __vfprintf_internal (vfprintf-internal.c:1517)
==23681==    by 0x48DE79E: printf (printf.c:33)
==23681==    by 0x4876800: txt_write_in_stdout (in /usr/lib/libcommons.so)
==23681==    by 0x4877570: _log_write_in_level (in /usr/lib/libcommons.so)
==23681==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==23681==    by 0x10A8C6: main (main.c:21)
==23681==  Block was alloc'd by thread #1
==23681== 
==23681== 
==23681== Process terminating with default action of signal 2 (SIGINT)
==23681==    at 0x490F117: __futex_abstimed_wait_common64 (futex-internal.c:57)
==23681==    by 0x490F117: __futex_abstimed_wait_common (futex-internal.c:87)
==23681==    by 0x490F117: __futex_abstimed_wait_cancelable64 (futex-internal.c:139)
==23681==    by 0x491AC77: __new_sem_wait_slow64.constprop.0 (sem_waitcommon.c:183)
==23681==    by 0x48540A8: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==23681==    by 0x10A939: main (main.c:27)
==23681== 
==23681== Use --history-level=approx or =none to gain increased speed, at
==23681== the cost of reduced accuracy of conflicting-access information
==23681== For lists of detected and suppressed errors, rerun with: -s
==23681== ERROR SUMMARY: 3355544 errors from 5 contexts (suppressed: 1054458 from 131)
