==38944== Helgrind, a thread error detector
==38944== Copyright (C) 2007-2017, and GNU GPL'd, by OpenWorks LLP et al.
==38944== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==38944== Command: ./bin/cpu ./configs/prueba.config
==38944== Parent PID: 27237
==38944== 
==38944== ---Thread-Announcement------------------------------------------
==38944== 
==38944== Thread #3 was created
==38944==    at 0x49A39F3: clone (clone.S:76)
==38944==    by 0x49A48EE: __clone_internal (clone-internal.c:83)
==38944==    by 0x49126D8: create_thread (pthread_create.c:295)
==38944==    by 0x49131FF: pthread_create@@GLIBC_2.34 (pthread_create.c:828)
==38944==    by 0x4853767: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38944==    by 0x10EA27: hilos_cpu (server.c:262)
==38944==    by 0x10A964: main (main.c:28)
==38944== 
==38944== ---Thread-Announcement------------------------------------------
==38944== 
==38944== Thread #2 was created
==38944==    at 0x49A39F3: clone (clone.S:76)
==38944==    by 0x49A48EE: __clone_internal (clone-internal.c:83)
==38944==    by 0x49126D8: create_thread (pthread_create.c:295)
==38944==    by 0x49131FF: pthread_create@@GLIBC_2.34 (pthread_create.c:828)
==38944==    by 0x4853767: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38944==    by 0x10E9A3: hilos_cpu (server.c:252)
==38944==    by 0x10A964: main (main.c:28)
==38944== 
==38944== ---Thread-Announcement------------------------------------------
==38944== 
==38944== Thread #1 is the program's root thread
==38944== 
==38944== ----------------------------------------------------------------
==38944== 
==38944== Possible data race during write of size 1 at 0x4AABE07 by thread #3
==38944== Locks held: none
==38944==    at 0x4859796: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38944==    by 0x4909664: _IO_new_file_xsputn (fileops.c:1235)
==38944==    by 0x4909664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==38944==    by 0x48FDA9C: fputs (iofputs.c:38)
==38944==    by 0x48767C6: txt_write_in_file (in /usr/lib/libcommons.so)
==38944==    by 0x4877522: _log_write_in_level (in /usr/lib/libcommons.so)
==38944==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==38944==    by 0x11106A: crear_conexion (sockets.c:163)
==38944==    by 0x10E60C: cliente_cpu_memoria (server.c:154)
==38944==    by 0x10E841: funcion_hilo_cliente_memoria (server.c:212)
==38944==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38944==    by 0x4912AC2: start_thread (pthread_create.c:442)
==38944==    by 0x49A3A03: clone (clone.S:100)
==38944== 
==38944== This conflicts with a previous write of size 1 by thread #2
==38944== Locks held: none
==38944==    at 0x4859796: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38944==    by 0x4909664: _IO_new_file_xsputn (fileops.c:1235)
==38944==    by 0x4909664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==38944==    by 0x48FDA9C: fputs (iofputs.c:38)
==38944==    by 0x48767C6: txt_write_in_file (in /usr/lib/libcommons.so)
==38944==    by 0x4877522: _log_write_in_level (in /usr/lib/libcommons.so)
==38944==    by 0x4877027: log_trace (in /usr/lib/libcommons.so)
==38944==    by 0x110CAC: iniciar_servidor (sockets.c:49)
==38944==    by 0x10E218: servidor_CPU_Kernel (server.c:75)
==38944==  Address 0x4aabe07 is 55 bytes inside a block of size 4,096 alloc'd
==38944==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38944==    by 0x48FCBA3: _IO_file_doallocate (filedoalloc.c:101)
==38944==    by 0x490BCDF: _IO_doallocbuf (genops.c:347)
==38944==    by 0x490AF5F: _IO_file_overflow@@GLIBC_2.2.5 (fileops.c:744)
==38944==    by 0x49096D4: _IO_new_file_xsputn (fileops.c:1243)
==38944==    by 0x49096D4: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==38944==    by 0x48FDA9C: fputs (iofputs.c:38)
==38944==    by 0x48767C6: txt_write_in_file (in /usr/lib/libcommons.so)
==38944==    by 0x4877522: _log_write_in_level (in /usr/lib/libcommons.so)
==38944==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==38944==    by 0x10A902: main (main.c:24)
==38944==  Block was alloc'd by thread #1
==38944== 
==38944== ----------------------------------------------------------------
==38944== 
==38944== Possible data race during write of size 1 at 0x4AAA6B0 by thread #3
==38944== Locks held: none
==38944==    at 0x48597B4: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38944==    by 0x4909664: _IO_new_file_xsputn (fileops.c:1235)
==38944==    by 0x4909664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==38944==    by 0x48F500B: outstring_func (vfprintf-internal.c:239)
==38944==    by 0x48F500B: __vfprintf_internal (vfprintf-internal.c:1517)
==38944==    by 0x48DE79E: printf (printf.c:33)
==38944==    by 0x4876800: txt_write_in_stdout (in /usr/lib/libcommons.so)
==38944==    by 0x4877570: _log_write_in_level (in /usr/lib/libcommons.so)
==38944==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==38944==    by 0x11106A: crear_conexion (sockets.c:163)
==38944==    by 0x10E60C: cliente_cpu_memoria (server.c:154)
==38944==    by 0x10E841: funcion_hilo_cliente_memoria (server.c:212)
==38944==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38944==    by 0x4912AC2: start_thread (pthread_create.c:442)
==38944== 
==38944== This conflicts with a previous write of size 1 by thread #2
==38944== Locks held: none
==38944==    at 0x48597B4: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38944==    by 0x4909664: _IO_new_file_xsputn (fileops.c:1235)
==38944==    by 0x4909664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==38944==    by 0x48F500B: outstring_func (vfprintf-internal.c:239)
==38944==    by 0x48F500B: __vfprintf_internal (vfprintf-internal.c:1517)
==38944==    by 0x48DE79E: printf (printf.c:33)
==38944==    by 0x4876800: txt_write_in_stdout (in /usr/lib/libcommons.so)
==38944==    by 0x4877570: _log_write_in_level (in /usr/lib/libcommons.so)
==38944==    by 0x4877027: log_trace (in /usr/lib/libcommons.so)
==38944==    by 0x110CAC: iniciar_servidor (sockets.c:49)
==38944==  Address 0x4aaa6b0 is 0 bytes inside a block of size 1,024 alloc'd
==38944==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38944==    by 0x48FCBA3: _IO_file_doallocate (filedoalloc.c:101)
==38944==    by 0x490BCDF: _IO_doallocbuf (genops.c:347)
==38944==    by 0x490AF5F: _IO_file_overflow@@GLIBC_2.2.5 (fileops.c:744)
==38944==    by 0x49096D4: _IO_new_file_xsputn (fileops.c:1243)
==38944==    by 0x49096D4: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==38944==    by 0x48F500B: outstring_func (vfprintf-internal.c:239)
==38944==    by 0x48F500B: __vfprintf_internal (vfprintf-internal.c:1517)
==38944==    by 0x48DE79E: printf (printf.c:33)
==38944==    by 0x4876800: txt_write_in_stdout (in /usr/lib/libcommons.so)
==38944==    by 0x4877570: _log_write_in_level (in /usr/lib/libcommons.so)
==38944==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==38944==    by 0x10A902: main (main.c:24)
==38944==  Block was alloc'd by thread #1
==38944== 
==38944== ---Thread-Announcement------------------------------------------
==38944== 
==38944== Thread #5 was created
==38944==    at 0x49A39F3: clone (clone.S:76)
==38944==    by 0x49A48EE: __clone_internal (clone-internal.c:83)
==38944==    by 0x49126D8: create_thread (pthread_create.c:295)
==38944==    by 0x49131FF: pthread_create@@GLIBC_2.34 (pthread_create.c:828)
==38944==    by 0x4853767: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38944==    by 0x10AA3E: iniciar_cpu (cicloDeInstruccion.c:25)
==38944==    by 0x10A975: main (main.c:30)
==38944== 
==38944== ---Thread-Announcement------------------------------------------
==38944== 
==38944== Thread #4 was created
==38944==    at 0x49A39F3: clone (clone.S:76)
==38944==    by 0x49A48EE: __clone_internal (clone-internal.c:83)
==38944==    by 0x49126D8: create_thread (pthread_create.c:295)
==38944==    by 0x49131FF: pthread_create@@GLIBC_2.34 (pthread_create.c:828)
==38944==    by 0x4853767: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38944==    by 0x10A9DC: iniciar_cpu (cicloDeInstruccion.c:16)
==38944==    by 0x10A975: main (main.c:30)
==38944== 
==38944== ----------------------------------------------------------------
==38944== 
==38944== Possible data race during write of size 1 at 0x4AAA6CD by thread #5
==38944== Locks held: none
==38944==    at 0x4859796: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38944==    by 0x4909664: _IO_new_file_xsputn (fileops.c:1235)
==38944==    by 0x4909664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==38944==    by 0x48F314C: outstring_func (vfprintf-internal.c:239)
==38944==    by 0x48F314C: __vfprintf_internal (vfprintf-internal.c:1263)
==38944==    by 0x48DE79E: printf (printf.c:33)
==38944==    by 0x10F743: send_paquete_syscall_sin_parametros (serializacion.c:237)
==38944==    by 0x10ECC5: recibir_kernel_interrupt (server.c:317)
==38944==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38944==    by 0x4912AC2: start_thread (pthread_create.c:442)
==38944==    by 0x49A3A03: clone (clone.S:100)
==38944== 
==38944== This conflicts with a previous write of size 1 by thread #4
==38944== Locks held: none
==38944==    at 0x48597B4: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38944==    by 0x4909664: _IO_new_file_xsputn (fileops.c:1235)
==38944==    by 0x4909664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==38944==    by 0x48F500B: outstring_func (vfprintf-internal.c:239)
==38944==    by 0x48F500B: __vfprintf_internal (vfprintf-internal.c:1517)
==38944==    by 0x48DE79E: printf (printf.c:33)
==38944==    by 0x4876800: txt_write_in_stdout (in /usr/lib/libcommons.so)
==38944==    by 0x4877570: _log_write_in_level (in /usr/lib/libcommons.so)
==38944==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==38944==    by 0x10D390: traducir_direccion_logica (mmu.c:8)
==38944==  Address 0x4aaa6cd is 29 bytes inside a block of size 1,024 alloc'd
==38944==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38944==    by 0x48FCBA3: _IO_file_doallocate (filedoalloc.c:101)
==38944==    by 0x490BCDF: _IO_doallocbuf (genops.c:347)
==38944==    by 0x490AF5F: _IO_file_overflow@@GLIBC_2.2.5 (fileops.c:744)
==38944==    by 0x49096D4: _IO_new_file_xsputn (fileops.c:1243)
==38944==    by 0x49096D4: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==38944==    by 0x48F500B: outstring_func (vfprintf-internal.c:239)
==38944==    by 0x48F500B: __vfprintf_internal (vfprintf-internal.c:1517)
==38944==    by 0x48DE79E: printf (printf.c:33)
==38944==    by 0x4876800: txt_write_in_stdout (in /usr/lib/libcommons.so)
==38944==    by 0x4877570: _log_write_in_level (in /usr/lib/libcommons.so)
==38944==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==38944==    by 0x10A902: main (main.c:24)
==38944==  Block was alloc'd by thread #1
==38944== 
==38944== ----------------------------------------------------------------
==38944== 
==38944== Possible data race during write of size 1 at 0x4AAA6CE by thread #5
==38944== Locks held: none
==38944==    at 0x48597B4: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38944==    by 0x4909664: _IO_new_file_xsputn (fileops.c:1235)
==38944==    by 0x4909664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==38944==    by 0x48F3CA8: outstring_func (vfprintf-internal.c:239)
==38944==    by 0x48F3CA8: __vfprintf_internal (vfprintf-internal.c:1516)
==38944==    by 0x48DE79E: printf (printf.c:33)
==38944==    by 0x10F743: send_paquete_syscall_sin_parametros (serializacion.c:237)
==38944==    by 0x10ECC5: recibir_kernel_interrupt (server.c:317)
==38944==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38944==    by 0x4912AC2: start_thread (pthread_create.c:442)
==38944==    by 0x49A3A03: clone (clone.S:100)
==38944== 
==38944== This conflicts with a previous write of size 1 by thread #4
==38944== Locks held: none
==38944==    at 0x48597B4: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38944==    by 0x4909664: _IO_new_file_xsputn (fileops.c:1235)
==38944==    by 0x4909664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==38944==    by 0x48F500B: outstring_func (vfprintf-internal.c:239)
==38944==    by 0x48F500B: __vfprintf_internal (vfprintf-internal.c:1517)
==38944==    by 0x48DE79E: printf (printf.c:33)
==38944==    by 0x4876800: txt_write_in_stdout (in /usr/lib/libcommons.so)
==38944==    by 0x4877570: _log_write_in_level (in /usr/lib/libcommons.so)
==38944==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==38944==    by 0x10D390: traducir_direccion_logica (mmu.c:8)
==38944==  Address 0x4aaa6ce is 30 bytes inside a block of size 1,024 alloc'd
==38944==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38944==    by 0x48FCBA3: _IO_file_doallocate (filedoalloc.c:101)
==38944==    by 0x490BCDF: _IO_doallocbuf (genops.c:347)
==38944==    by 0x490AF5F: _IO_file_overflow@@GLIBC_2.2.5 (fileops.c:744)
==38944==    by 0x49096D4: _IO_new_file_xsputn (fileops.c:1243)
==38944==    by 0x49096D4: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==38944==    by 0x48F500B: outstring_func (vfprintf-internal.c:239)
==38944==    by 0x48F500B: __vfprintf_internal (vfprintf-internal.c:1517)
==38944==    by 0x48DE79E: printf (printf.c:33)
==38944==    by 0x4876800: txt_write_in_stdout (in /usr/lib/libcommons.so)
==38944==    by 0x4877570: _log_write_in_level (in /usr/lib/libcommons.so)
==38944==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==38944==    by 0x10A902: main (main.c:24)
==38944==  Block was alloc'd by thread #1
==38944== 
==38944== ----------------------------------------------------------------
==38944== 
==38944== Thread #1's call to pthread_mutex_lock failed
==38944==    with error code 22 (EINVAL: Invalid argument)
==38944==    at 0x4850D30: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38944==    by 0x10CECB: terminar_programa (auxiliares.c:87)
==38944==    by 0x10A99D: main (main.c:35)
==38944== 
==38944== ----------------------------------------------------------------
==38944== 
==38944== Thread #1 unlocked an invalid lock at 0x1171A0
==38944==    at 0x48511E6: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38944==    by 0x10CEF8: terminar_programa (auxiliares.c:89)
==38944==    by 0x10A99D: main (main.c:35)
==38944== 
==38944== ----------------------------------------------------------------
==38944== 
==38944== Thread #1's call to pthread_mutex_unlock failed
==38944==    with error code 22 (EINVAL: Invalid argument)
==38944==    at 0x4851311: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38944==    by 0x10CEF8: terminar_programa (auxiliares.c:89)
==38944==    by 0x10A99D: main (main.c:35)
==38944== 
==38944== ----------------------------------------------------------------
==38944== 
==38944== Thread #1's call to pthread_mutex_lock failed
==38944==    with error code 22 (EINVAL: Invalid argument)
==38944==    at 0x4850D30: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38944==    by 0x10CF16: terminar_programa (auxiliares.c:91)
==38944==    by 0x10A99D: main (main.c:35)
==38944== 
==38944== ----------------------------------------------------------------
==38944== 
==38944== Thread #1 unlocked an invalid lock at 0x1171A0
==38944==    at 0x48511E6: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38944==    by 0x10CF34: terminar_programa (auxiliares.c:93)
==38944==    by 0x10A99D: main (main.c:35)
==38944== 
==38944== ----------------------------------------------------------------
==38944== 
==38944== Thread #1's call to pthread_mutex_unlock failed
==38944==    with error code 22 (EINVAL: Invalid argument)
==38944==    at 0x4851311: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38944==    by 0x10CF34: terminar_programa (auxiliares.c:93)
==38944==    by 0x10A99D: main (main.c:35)
==38944== 
==38944== 
==38944== Use --history-level=approx or =none to gain increased speed, at
==38944== the cost of reduced accuracy of conflicting-access information
==38944== For lists of detected and suppressed errors, rerun with: -s
==38944== ERROR SUMMARY: 16512 errors from 10 contexts (suppressed: 245060 from 350)
